name: Release

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发

jobs:
  build:
    runs-on: windows-latest
    env:
      VERSION: ${{ secrets.VERSION }}

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 环境
        run: |
          echo ${{ github.workspace }}
          echo ${{ github.ref_name }}

      - name: 复制资源
        run: |
          cd ../
          git clone https://${VERSION}:x-oauth-basic@github.com/NGC2237plus/version_test.git
          tree /F
          cd version_test/
